name: Update Extension

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download repository as .zip
        run: |
          wget https://github.com/randomstuff69/blooketbotextension/archive/refs/heads/main.zip -O extension.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: Automatic release for extension update
